Erkennung und Unterstützung für libcdio eingebaut

diff --git a/lib/trunk/configure b/lib/trunk/configure
--- a/lib/trunk/configure
+++ b/lib/trunk/configure
@@ -706,6 +706,10 @@ ICONV_LIBS
 ICONV_CFLAGS
 LTLIBICONV
 LIBICONV
+LIBCDIO_LDFLAGS
+LIBCDIO_CFLAGS
+libcdio_LIBS
+libcdio_CFLAGS
 SHOUTCONFIG
 PKGCONFIG
 SHOUT_LIBS
@@ -897,6 +901,7 @@ with_ogg
 with_ogg_libraries
 with_ogg_includes
 enable_oggtest
+with_libcdio
 with_gnu_ld
 enable_rpath
 with_libiconv_prefix
@@ -940,6 +945,8 @@ JPEG_CFLAGS
 JPEG_LIBS
 PNG_CFLAGS
 PNG_LIBS
+libcdio_CFLAGS
+libcdio_LIBS
 SDL2_CFLAGS
 SDL2_LIBS'
 
@@ -1608,6 +1615,7 @@ Optional Packages:
                           (optional)
   --with-ogg-includes=DIR Directory where libogg header files are installed
                           (optional)
+  --with-libcdio[=PATH]   support accesing audio cds (optional)
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-libiconv-prefix[=DIR]  search for libiconv in DIR/include and DIR/lib
   --without-libiconv-prefix     don't search for libiconv in includedir and libdir
@@ -1658,6 +1666,10 @@ Some influential environment variables:
   JPEG_LIBS   linker flags for JPEG, overriding pkg-config
   PNG_CFLAGS  C compiler flags for PNG, overriding pkg-config
   PNG_LIBS    linker flags for PNG, overriding pkg-config
+  libcdio_CFLAGS
+              C compiler flags for libcdio, overriding pkg-config
+  libcdio_LIBS
+              linker flags for libcdio, overriding pkg-config
   SDL2_CFLAGS C compiler flags for SDL2, overriding pkg-config
   SDL2_LIBS   linker flags for SDL2, overriding pkg-config
 
@@ -3682,6 +3694,8 @@ ac_config_headers="$ac_config_headers include/ppl7-config.h"
 # XIPH_PATH_SHOUT([ACTION-IF-FOUND [, ACTION-IF-NOT-FOUND]])
 # Test for libshout, and define SHOUT_CPPFLAGS SHOUT_CFLAGS SHOUT_LIBS, and
 # SHOUT_THREADSAFE
+
+
 
 
 
@@ -14186,6 +14200,218 @@ then
 fi
 
 
+report_have_libcdio="no"
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if we should use libcdio" >&5
+$as_echo_n "checking if we should use libcdio... " >&6; }
+
+
+# Check whether --with-libcdio was given.
+if test "${with_libcdio+set}" = set; then :
+  withval=$with_libcdio; libcdio_prefix="$withval"
+else
+  libcdio_prefix="auto"
+fi
+
+
+	have_libcdio="no"
+
+	if test "$libcdio_prefix" != "no"
+	then
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+		am_save_CPPFLAGS="$CPPFLAGS"
+		am_save_LIBS="$LIBS"
+		am_save_LDFLAGS="$LDFLAGS"
+
+		if test -n "$libcdio_prefix" -a "$libcdio_prefix" != "yes" -a "$libcdio_prefix" != "auto"
+		then
+		    LIBCDIO_CFLAGS="-I$with_libcdio/include"
+		    LIBCDIO_LDFLAGS="-L$with_libcdio/lib -lcdio "
+		else
+			# Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKGCONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKGCONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKGCONFIG="$PKGCONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKGCONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_PKGCONFIG" && ac_cv_path_PKGCONFIG="no"
+  ;;
+esac
+fi
+PKGCONFIG=$ac_cv_path_PKGCONFIG
+if test -n "$PKGCONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKGCONFIG" >&5
+$as_echo "$PKGCONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+			if test "$PKGCONFIG" != "no" && `$PKGCONFIG --exists libcdio`
+			then
+				LIBCDIO_CFLAGS=`$PKGCONFIG --cflags libcdio `
+		    	LIBCDIO_LDFLAGS=`$PKGCONFIG --libs libcdio `
+		    	else
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for libcdio" >&5
+$as_echo_n "checking for libcdio... " >&6; }
+
+if test -n "$libcdio_CFLAGS"; then
+    pkg_cv_libcdio_CFLAGS="$libcdio_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libcdio\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libcdio") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_libcdio_CFLAGS=`$PKG_CONFIG --cflags "libcdio" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libcdio_LIBS"; then
+    pkg_cv_libcdio_LIBS="$libcdio_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libcdio\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libcdio") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_libcdio_LIBS=`$PKG_CONFIG --libs "libcdio" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libcdio_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libcdio" 2>&1`
+        else
+	        libcdio_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libcdio" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libcdio_PKG_ERRORS" >&5
+
+	LIBCDIO_LDFLAGS="-lcdio "
+
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	LIBCDIO_LDFLAGS="-lcdio "
+
+else
+	libcdio_CFLAGS=$pkg_cv_libcdio_CFLAGS
+	libcdio_LIBS=$pkg_cv_libcdio_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	LIBCDIO_CFLAGS=$libcdio_CFLAGS
+					LIBCDIO_LDFLAGS=$libcdio_LIBS
+
+fi
+			fi
+		fi
+
+		CFLAGS="$CFLAGS $LIBCDIO_CFLAGS"
+		LDFLAGS="$LDFLAGS $LIBCDIO_LDFLAGS"
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if we can link against libcdio" >&5
+$as_echo_n "checking if we can link against libcdio... " >&6; }
+		cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+			#include <stdio.h>
+			#include <cdio/cdio.h>
+
+int
+main ()
+{
+
+			int main(int argc, char **argv) {
+				CdIo_t *p_cdio = cdio_open (NULL, DRIVER_DEVICE);
+			}
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+				have_libcdio="yes"
+
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+
+
+		CPPFLAGS=$am_save_CPPFLAGS
+		LIBS=$am_save_LIBS
+		LDFLAGS=$am_save_LDFLAGS
+	else
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	fi
+	if test $have_libcdio = "yes"
+	then
+
+$as_echo "#define HAVE_LIBCDIO 1" >>confdefs.h
+
+		report_have_libcdio="yes"
+	else
+		LIBCDIO_CFLAGS=""
+		LIBCDIO_LDFLAGS=""
+		:
+	fi
+
+
+
+
 
 
 
@@ -18706,6 +18932,7 @@ fi
 **   mpg123 library:       $report_have_mpg123
 **   ogg library:          $report_have_libogg
 **   shout library:        $report_have_libshout
+**   cdio library:         $report_have_libcdio
 **
 ** Cryptography:
 **   Libgcrypt:            $report_have_libgcrypt
@@ -18773,6 +19000,7 @@ $as_echo "
 **   mpg123 library:       $report_have_mpg123
 **   ogg library:          $report_have_libogg
 **   shout library:        $report_have_libshout
+**   cdio library:         $report_have_libcdio
 **
 ** Cryptography:
 **   Libgcrypt:            $report_have_libgcrypt
